/*
 * This file is generated by jOOQ.
 */
package com.tandem.jooq.tables.records;


import com.tandem.jooq.tables.Permissions;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PermissionsRecord extends UpdatableRecordImpl<PermissionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.permissions.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.permissions.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.permissions.user_id</code>.
     */
    public void setUserId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.permissions.user_id</code>.
     */
    public UUID getUserId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.permissions.resource</code>.
     */
    public void setResource(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.permissions.resource</code>.
     */
    public String getResource() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.permissions.action</code>.
     */
    public void setAction(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.permissions.action</code>.
     */
    public String getAction() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.permissions.granted_at</code>.
     */
    public void setGrantedAt(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.permissions.granted_at</code>.
     */
    public LocalDateTime getGrantedAt() {
        return (LocalDateTime) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PermissionsRecord
     */
    public PermissionsRecord() {
        super(Permissions.PERMISSIONS);
    }

    /**
     * Create a detached, initialised PermissionsRecord
     */
    public PermissionsRecord(UUID id, UUID userId, String resource, String action, LocalDateTime grantedAt) {
        super(Permissions.PERMISSIONS);

        setId(id);
        setUserId(userId);
        setResource(resource);
        setAction(action);
        setGrantedAt(grantedAt);
        resetChangedOnNotNull();
    }
}
