/*
 * This file is generated by jOOQ.
 */
package com.tandem.jooq.tables.records;


import com.tandem.jooq.tables.Sessions;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class SessionsRecord extends UpdatableRecordImpl<SessionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.sessions.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.sessions.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.sessions.user_id</code>.
     */
    public void setUserId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.sessions.user_id</code>.
     */
    public UUID getUserId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.sessions.access_token_hash</code>.
     */
    public void setAccessTokenHash(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.sessions.access_token_hash</code>.
     */
    public String getAccessTokenHash() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.sessions.refresh_token_hash</code>.
     */
    public void setRefreshTokenHash(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.sessions.refresh_token_hash</code>.
     */
    public String getRefreshTokenHash() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.sessions.device_info</code>.
     */
    public void setDeviceInfo(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.sessions.device_info</code>.
     */
    public String getDeviceInfo() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.sessions.ip_address</code>.
     */
    public void setIpAddress(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.sessions.ip_address</code>.
     */
    public String getIpAddress() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.sessions.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.sessions.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>public.sessions.expires_at</code>.
     */
    public void setExpiresAt(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.sessions.expires_at</code>.
     */
    public LocalDateTime getExpiresAt() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>public.sessions.revoked_at</code>.
     */
    public void setRevokedAt(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.sessions.revoked_at</code>.
     */
    public LocalDateTime getRevokedAt() {
        return (LocalDateTime) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SessionsRecord
     */
    public SessionsRecord() {
        super(Sessions.SESSIONS);
    }

    /**
     * Create a detached, initialised SessionsRecord
     */
    public SessionsRecord(UUID id, UUID userId, String accessTokenHash, String refreshTokenHash, String deviceInfo, String ipAddress, LocalDateTime createdAt, LocalDateTime expiresAt, LocalDateTime revokedAt) {
        super(Sessions.SESSIONS);

        setId(id);
        setUserId(userId);
        setAccessTokenHash(accessTokenHash);
        setRefreshTokenHash(refreshTokenHash);
        setDeviceInfo(deviceInfo);
        setIpAddress(ipAddress);
        setCreatedAt(createdAt);
        setExpiresAt(expiresAt);
        setRevokedAt(revokedAt);
        resetChangedOnNotNull();
    }
}
