/*
 * This file is generated by jOOQ.
 */
package com.tandem.jooq.tables.records;


import com.tandem.jooq.tables.Users;

import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class UsersRecord extends UpdatableRecordImpl<UsersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.users.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.users.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.users.phone_number</code>.
     */
    public void setPhoneNumber(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.users.phone_number</code>.
     */
    public String getPhoneNumber() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.users.email</code>.
     */
    public void setEmail(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.users.email</code>.
     */
    public String getEmail() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.users.password_hash</code>.
     */
    public void setPasswordHash(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.users.password_hash</code>.
     */
    public String getPasswordHash() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.users.email_verified</code>.
     */
    public void setEmailVerified(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.users.email_verified</code>.
     */
    public Boolean getEmailVerified() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>public.users.phone_verified</code>.
     */
    public void setPhoneVerified(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.users.phone_verified</code>.
     */
    public Boolean getPhoneVerified() {
        return (Boolean) get(5);
    }

    /**
     * Setter for <code>public.users.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.users.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>public.users.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.users.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>public.users.last_login_at</code>.
     */
    public void setLastLoginAt(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.users.last_login_at</code>.
     */
    public LocalDateTime getLastLoginAt() {
        return (LocalDateTime) get(8);
    }

    /**
     * Setter for <code>public.users.status</code>.
     */
    public void setStatus(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.users.status</code>.
     */
    public String getStatus() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsersRecord
     */
    public UsersRecord() {
        super(Users.USERS);
    }

    /**
     * Create a detached, initialised UsersRecord
     */
    public UsersRecord(UUID id, String phoneNumber, String email, String passwordHash, Boolean emailVerified, Boolean phoneVerified, LocalDateTime createdAt, LocalDateTime updatedAt, LocalDateTime lastLoginAt, String status) {
        super(Users.USERS);

        setId(id);
        setPhoneNumber(phoneNumber);
        setEmail(email);
        setPasswordHash(passwordHash);
        setEmailVerified(emailVerified);
        setPhoneVerified(phoneVerified);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        setLastLoginAt(lastLoginAt);
        setStatus(status);
        resetChangedOnNotNull();
    }
}
