services:

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_pass
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U auth_user -d auth_db"]
      interval: 5s
      retries: 10
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - tandem-network

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - tandem-network
  auth_service:
    build: .
    container_name: auth_service
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    ports:
      - "8082:8080"
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/auth_db
      SPRING_DATASOURCE_USERNAME: auth_user
      SPRING_DATASOURCE_PASSWORD: auth_pass
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      PRIVATE_KEY: ${PRIVATE_KEY}
    networks:
      - tandem-network

volumes:
  postgres_data:

networks:
  tandem-network:
    driver: bridge