services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: ProfileService      # <- Имя БД
      POSTGRES_USER: postgres          # <- Пользователь  
      POSTGRES_PASSWORD: koroleva      # <- Пароль
    ports:
      - "5432:5432"
    profiles: [ "new-dev" ]