/*
 * This file is generated by jOOQ.
 */
package com.tandem.jooq.tables;


import com.tandem.jooq.Indexes;
import com.tandem.jooq.Keys;
import com.tandem.jooq.Public;
import com.tandem.jooq.tables.records.PermissionsRecord;

import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Permissions extends TableImpl<PermissionsRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.permissions</code>
     */
    public static final Permissions PERMISSIONS = new Permissions();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PermissionsRecord> getRecordType() {
        return PermissionsRecord.class;
    }

    /**
     * The column <code>public.permissions.id</code>.
     */
    public final TableField<PermissionsRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.permissions.user_id</code>.
     */
    public final TableField<PermissionsRecord, UUID> USER_ID = createField(DSL.name("user_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.permissions.resource</code>.
     */
    public final TableField<PermissionsRecord, String> RESOURCE = createField(DSL.name("resource"), SQLDataType.VARCHAR(100).nullable(false), this, "");

    /**
     * The column <code>public.permissions.action</code>.
     */
    public final TableField<PermissionsRecord, String> ACTION = createField(DSL.name("action"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.permissions.granted_at</code>.
     */
    public final TableField<PermissionsRecord, LocalDateTime> GRANTED_AT = createField(DSL.name("granted_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    private Permissions(Name alias, Table<PermissionsRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Permissions(Name alias, Table<PermissionsRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.permissions</code> table reference
     */
    public Permissions(String alias) {
        this(DSL.name(alias), PERMISSIONS);
    }

    /**
     * Create an aliased <code>public.permissions</code> table reference
     */
    public Permissions(Name alias) {
        this(alias, PERMISSIONS);
    }

    /**
     * Create a <code>public.permissions</code> table reference
     */
    public Permissions() {
        this(DSL.name("permissions"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_PERMISSIONS_USER_ID);
    }

    @Override
    public UniqueKey<PermissionsRecord> getPrimaryKey() {
        return Keys.PERMISSIONS_PKEY;
    }

    @Override
    public List<UniqueKey<PermissionsRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.PERMISSIONS_USER_ID_RESOURCE_ACTION_KEY);
    }

    @Override
    public Permissions as(String alias) {
        return new Permissions(DSL.name(alias), this);
    }

    @Override
    public Permissions as(Name alias) {
        return new Permissions(alias, this);
    }

    @Override
    public Permissions as(Table<?> alias) {
        return new Permissions(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Permissions rename(String name) {
        return new Permissions(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Permissions rename(Name name) {
        return new Permissions(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Permissions rename(Table<?> name) {
        return new Permissions(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Permissions where(Condition condition) {
        return new Permissions(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Permissions where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Permissions where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Permissions where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Permissions where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Permissions where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Permissions where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Permissions where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Permissions whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Permissions whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
