/*
 * This file is generated by jOOQ.
 */
package com.tandem.jooq;


import com.tandem.jooq.tables.FlywaySchemaHistory;
import com.tandem.jooq.tables.Permissions;
import com.tandem.jooq.tables.Sessions;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index FLYWAY_SCHEMA_HISTORY_S_IDX = Internal.createIndex(DSL.name("flyway_schema_history_s_idx"), FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, new OrderField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.SUCCESS }, false);
    public static final Index IDX_PERMISSIONS_USER_ID = Internal.createIndex(DSL.name("idx_permissions_user_id"), Permissions.PERMISSIONS, new OrderField[] { Permissions.PERMISSIONS.USER_ID }, false);
    public static final Index IDX_SESSIONS_ACCESS_HASH = Internal.createIndex(DSL.name("idx_sessions_access_hash"), Sessions.SESSIONS, new OrderField[] { Sessions.SESSIONS.ACCESS_TOKEN_HASH }, true);
    public static final Index IDX_SESSIONS_EXPIRES_AT = Internal.createIndex(DSL.name("idx_sessions_expires_at"), Sessions.SESSIONS, new OrderField[] { Sessions.SESSIONS.EXPIRES_AT }, false);
    public static final Index IDX_SESSIONS_REFRESH_HASH = Internal.createIndex(DSL.name("idx_sessions_refresh_hash"), Sessions.SESSIONS, new OrderField[] { Sessions.SESSIONS.REFRESH_TOKEN_HASH }, true);
    public static final Index IDX_SESSIONS_USER_ID = Internal.createIndex(DSL.name("idx_sessions_user_id"), Sessions.SESSIONS, new OrderField[] { Sessions.SESSIONS.USER_ID }, false);
}
