/*
 * This file is generated by jOOQ.
 */
package com.tandem.jooq;


import com.tandem.jooq.tables.FlywaySchemaHistory;
import com.tandem.jooq.tables.Permissions;
import com.tandem.jooq.tables.Sessions;
import com.tandem.jooq.tables.Users;
import com.tandem.jooq.tables.records.FlywaySchemaHistoryRecord;
import com.tandem.jooq.tables.records.PermissionsRecord;
import com.tandem.jooq.tables.records.SessionsRecord;
import com.tandem.jooq.tables.records.UsersRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<FlywaySchemaHistoryRecord> FLYWAY_SCHEMA_HISTORY_PK = Internal.createUniqueKey(FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY, DSL.name("flyway_schema_history_pk"), new TableField[] { FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK }, true);
    public static final UniqueKey<PermissionsRecord> PERMISSIONS_PKEY = Internal.createUniqueKey(Permissions.PERMISSIONS, DSL.name("permissions_pkey"), new TableField[] { Permissions.PERMISSIONS.ID }, true);
    public static final UniqueKey<PermissionsRecord> PERMISSIONS_USER_ID_RESOURCE_ACTION_KEY = Internal.createUniqueKey(Permissions.PERMISSIONS, DSL.name("permissions_user_id_resource_action_key"), new TableField[] { Permissions.PERMISSIONS.USER_ID, Permissions.PERMISSIONS.RESOURCE, Permissions.PERMISSIONS.ACTION }, true);
    public static final UniqueKey<SessionsRecord> SESSIONS_PKEY = Internal.createUniqueKey(Sessions.SESSIONS, DSL.name("sessions_pkey"), new TableField[] { Sessions.SESSIONS.ID }, true);
    public static final UniqueKey<UsersRecord> USERS_EMAIL_KEY = Internal.createUniqueKey(Users.USERS, DSL.name("users_email_key"), new TableField[] { Users.USERS.EMAIL }, true);
    public static final UniqueKey<UsersRecord> USERS_PHONE_NUMBER_KEY = Internal.createUniqueKey(Users.USERS, DSL.name("users_phone_number_key"), new TableField[] { Users.USERS.PHONE_NUMBER }, true);
    public static final UniqueKey<UsersRecord> USERS_PKEY = Internal.createUniqueKey(Users.USERS, DSL.name("users_pkey"), new TableField[] { Users.USERS.ID }, true);
}
