/*
 * This file is generated by jOOQ.
 */
package com.tandem.jooq;


import com.tandem.jooq.tables.FlywaySchemaHistory;
import com.tandem.jooq.tables.Permissions;
import com.tandem.jooq.tables.Sessions;
import com.tandem.jooq.tables.Users;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.flyway_schema_history</code>.
     */
    public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY = FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

    /**
     * The table <code>public.permissions</code>.
     */
    public static final Permissions PERMISSIONS = Permissions.PERMISSIONS;

    /**
     * The table <code>public.sessions</code>.
     */
    public static final Sessions SESSIONS = Sessions.SESSIONS;

    /**
     * The table <code>public.users</code>.
     */
    public static final Users USERS = Users.USERS;
}
